//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDistributionOutlet.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class COUNTRY
    {
        public COUNTRY()
        {
            this.SHIPMENT = new HashSet<SHIPMENT>();
            this.SUPPLIER = new HashSet<SUPPLIER>();
        }
    
        public long countryID { get; set; }
        public string countryName { get; set; }
        public string countryAbbreviation { get; set; }
        public string countryFlag { get; set; }
    
        public virtual ICollection<SHIPMENT> SHIPMENT { get; set; }
        public virtual ICollection<SUPPLIER> SUPPLIER { get; set; }
    }
}
