//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDistributionOutlet.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT_DESCRIPTION_DETAIL
    {
        public long productDescriptionDetailsID { get; set; }
        public long productDescriptionID { get; set; }
        public string productColor { get; set; }
        public string productWeight { get; set; }
        public string productSize { get; set; }
        public string productPrice { get; set; }
    
        public virtual PRODUCT_DESCRIPTION PRODUCT_DESCRIPTION { get; set; }
    }
}
