//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDistributionOutlet.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT_BOXING_DETAILS
    {
        public long productBoxingDetailsID { get; set; }
        public long shipmentProductDetailsID { get; set; }
        public long numberOfBoxes { get; set; }
        public long numberOfPacks { get; set; }
        public long numberOfProducts { get; set; }
        public long numberOfProductsPerPack { get; set; }
        public long numberOfPacksPerBox { get; set; }
    
        public virtual SHIPMENT_PRODUCT_DETAIL SHIPMENT_PRODUCT_DETAIL { get; set; }
    }
}
