//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDistributionOutlet.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT_DESCRIPTION
    {
        public PRODUCT_DESCRIPTION()
        {
            this.PRODUCT_DESCRIPTION_DETAIL = new HashSet<PRODUCT_DESCRIPTION_DETAIL>();
        }
    
        public long productDescriptionID { get; set; }
        public long productID { get; set; }
        public string productDescLong { get; set; }
        public bool prodctCopied { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual ICollection<PRODUCT_DESCRIPTION_DETAIL> PRODUCT_DESCRIPTION_DETAIL { get; set; }
    }
}
