//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDistributionOutlet.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHIPMENT_PRODUCT_DETAIL
    {
        public SHIPMENT_PRODUCT_DETAIL()
        {
            this.PRODUCT_BOXING_DETAILS = new HashSet<PRODUCT_BOXING_DETAILS>();
        }
    
        public long shipmentProductDetailsID { get; set; }
        public Nullable<long> shipmentDetailsID { get; set; }
        public Nullable<long> productID { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual ICollection<PRODUCT_BOXING_DETAILS> PRODUCT_BOXING_DETAILS { get; set; }
        public virtual SHIPMENT_DETAIL SHIPMENT_DETAIL { get; set; }
    }
}
