//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDistributionOutlet.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHIPMENT
    {
        public SHIPMENT()
        {
            this.SHIPMENT_DETAIL = new HashSet<SHIPMENT_DETAIL>();
            this.SHIPMENT_SUPPLIER = new HashSet<SHIPMENT_SUPPLIER>();
        }
    
        public long shipmentID { get; set; }
        public Nullable<long> countryID { get; set; }
        public string shipmentCity { get; set; }
        public string shipmentProvince { get; set; }
    
        public virtual COUNTRY COUNTRY { get; set; }
        public virtual ICollection<SHIPMENT_DETAIL> SHIPMENT_DETAIL { get; set; }
        public virtual SHIPMENT SHIPMENT1 { get; set; }
        public virtual SHIPMENT SHIPMENT2 { get; set; }
        public virtual ICollection<SHIPMENT_SUPPLIER> SHIPMENT_SUPPLIER { get; set; }
    }
}
