//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDistributionOutlet.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHIPMENT_DETAIL
    {
        public SHIPMENT_DETAIL()
        {
            this.SHIPMENT_PRODUCT_DETAIL = new HashSet<SHIPMENT_PRODUCT_DETAIL>();
        }
    
        public long shipmentDetailsID { get; set; }
        public long shipmentID { get; set; }
        public Nullable<System.DateTime> shipmentDate { get; set; }
        public Nullable<System.DateTime> shipmentEstimatedArrivalDate { get; set; }
        public Nullable<System.DateTime> shipmentArrivalDate { get; set; }
        public string shipmentMethod { get; set; }
        public Nullable<long> numberOfProducts { get; set; }
    
        public virtual SHIPMENT SHIPMENT { get; set; }
        public virtual ICollection<SHIPMENT_PRODUCT_DETAIL> SHIPMENT_PRODUCT_DETAIL { get; set; }
    }
}
