//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDistributionOutlet.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUPPLIER
    {
        public SUPPLIER()
        {
            this.SHIPMENT_SUPPLIER = new HashSet<SHIPMENT_SUPPLIER>();
        }
    
        public long supplierID { get; set; }
        public string supplierName { get; set; }
        public long countryID { get; set; }
        public string supplierProvince { get; set; }
        public string supplierCity { get; set; }
        public string supplierPostalCode { get; set; }
        public string supplierTelephone { get; set; }
        public string supplierFax { get; set; }
        public string supplierEmail { get; set; }
        public string supplierStreet { get; set; }
        public string supplierUnitNumber { get; set; }
    
        public virtual COUNTRY COUNTRY { get; set; }
        public virtual ICollection<SHIPMENT_SUPPLIER> SHIPMENT_SUPPLIER { get; set; }
        public virtual SUPPLIER SUPPLIER1 { get; set; }
        public virtual SUPPLIER SUPPLIER2 { get; set; }
    }
}
